<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\ModelPack.cs" Link="ModelPack.cs" />
    <Compile Include="..\Motion.cs" Link="Motion.cs" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>
